### ISSUE TITLE
Cookie “next-auth.session-token”  is ignored due to reaching max size limit

### ISSUE THREAD

**Issue by Firas-Al-Azizy** [osmarpb97/strapi-nextauth-template#1]
Hello Mr.Osmar
I beg your pardon for reaching you throw the issues of this project out of nowhere just to seek help, but i tried to mail you on your previewed email in your profile and reached a dead-end,hopefully, you might help me with the problem I faced.

In your repository **strapi-nextauth-template**, you integrated Next-Auth with Strapi Jwt and used the local Starpi Postgres database o be able to keep persistent the accounts of users, but in my Next-js Strapi web application I separated the front-end from the back-end into different repositories and deployed the Strapi back-end to Heroku, so I took the connection string to the Postgres database that is located in Heroku , then I assigned it to the database property in [...nextauth.js] file, the site worked fine until I got this error **( Set-Cookie header is ignored in response from URL: http://localhost:3000/api/auth/callback/credentials?. Cookie length should be less than or equal to 4096 characters )**

I discoverer that there was no connection, so when I deleted the database property in [...nextauth.js] the site did not throw any error and worked with Strapi Jwt storing in the **Cookie “next-auth.session-token”** but it says that it reached its max size, then the login page redirects you to the login page, not allowing you to sign in to the site, I don't know why I surfed the internet for a solution but there was not any resource that mentioned the same problem.  

Thanx in advance for troubling you with reading my problem, I hope you can give some guidance

**Comment by osmarpb97** [comment]
Hello @Firas-Al-Azizy  I was so busy with one proyect, so i didnt read your comment i can help you to figure out whats the problem so you can contact me right now! Let me know where 💯

**Comment by Firas-Al-Azizy** [comment]
Thanks a lot for responding , I have mentioned my problem in the issues of nextauth repository
 [nextauth issue 2145](https://github.com/nextauthjs/next-auth/issues/2145)
 [nextauth issue 2146](https://github.com/nextauthjs/next-auth/issues/2146)
 [nextauth discussions 2148](https://github.com/nextauthjs/next-auth/discussions/2148)
 and they were mean to me, I still did not find an answer to solve the problem, the code I am using is the marvelous code you used in this template so I think they don't know how to deal with Strapi unlike you 
If you don't mind and If that is ok with you, Could I have a way to contact you through

**Comment by osmarpb97** [comment]
What type of data do you send to the user session/cookie?

**Comment by Firas-Al-Azizy** [comment]
This is my Login Component

[Login](https://codepen.io/firas-al-azizy/pen/abJPQeN)


This is the [...nextauth.js] file

[nextauth](https://codepen.io/firas-al-azizy/pen/YzZddKr)

**Comment by osmarpb97** [comment]
Do you already have some models implemented on Strapi? I think your problem is that the user data exceeds the cookie maxlenght

**Comment by Firas-Al-Azizy** [comment]
Yeah, my user table has a lot of relationships With other tables 
![user table](https://user-images.githubusercontent.com/43917135/122184863-50718d00-ce95-11eb-9de8-a35e3f5d8cdc.png)

 is there a way to only fetch the user table data without its relationships and send it to the cookie? .. only for the login
 
 the only data that I need to be stored in the session are:

-  JWT token
- user-id (small int)
- user-name (text)
- user-role id (small int)
- user-company  (text)
- user-subagent (boolean) 
- user-commotion 

this is the user object that I get after signing in
```
{
  user: {
    id: ...........,
    username: '.............,
    email: '..........',
    provider: 'local',
    confirmed: true,
    blocked: false,
    role: {
      id: 1,
      name: 'Admin',
      description: 'Admin',
      type: 'authenticated'
    },
    created_at: '2021-05-23T14:19:39.556Z',
    updated_at: '2021-06-16T13:38:33.013Z',
    phoneNumber: '.............',
    note: null,
    commissionRate: 1,
    address: null,
    company: '..........',
    application: null,
    file: null,
    logo: null,
    loglId: null,
    logoId: null,
    subagent: false,
    announcements: [],
    programs: [],
    students: [],
    universities: [],
    applications: [],
    notes: []
  },
  expires: '2021-07-16T13:45:46.090Z',
  jwt: '............'
}

**Comment by Firas-Al-Azizy** [comment]
Thanks a looooooot , i solved the problem,  because of your guidance 

I solved it by modifying the user data in [...nextauth.js] like this :
```
{let loginData = {
            jwt: "",
            user: {
              id: 0,
              username: "",
              email: "",
              provider: "",
              role: {
                id: 0,
                name: "",
                description: "",
                type: "",
              },
              created_at: "",
              updated_at: "",
              commissionRate: 0,
              company: "",
              subagent: true,
              confirmed: false,
              blocked: true,
            },
          };
          if (user.data) {
            (loginData.jwt = user.data.jwt),
            (loginData.user.id = user.data.user.id),
            (loginData.user.username = user.data.user.username);
            (loginData.user.email = user.data.user.email),
            (loginData.user.provider = user.data.user.provider),
            (loginData.user.role = user.data.user.role),
            (loginData.user.confirmed = user.data.user.confirmed),
            (loginData.user.blocked = user.data.user.blocked),
            (loginData.user.created_at = user.data.user.created_at),
            (loginData.user.updated_at = user.data.user.updated_at),
            (loginData.user.commissionRate = user.data.user.commissionRate),
            (loginData.user.company = user.data.user.company),
            (loginData.user.subagent = user.data.user.subagent);
            return loginData;
            }else{......}
            ```
I would appreciate it if you could give me a way to contact you to express my gratitude by  a gift,
you are the only one who helped me

**Comment by osmarpb97** [comment]
Yeah you can reach me at osmarpb.97@gmail.com
